[package]
name = "own_shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.95" 
dirs = "5.0"
libc = "0.2"
